version: '3'
services:
  ldap:
    image: ldap
    container_name: ldap
    build:
      context: ldap
    ports:
      - '389:389'
    environment:
      LDAP_DOMAIN: "example.org"
      LDAP_ADMIN_PASSWORD: "password"
  idp:
    image: idp 
    container_name: idp
    build:
      context: idp
    ports:
      - 443:8443
    environment:
      LDAP_HOST: "ldap"
  sp:
    image: sp
    container_name: sp
    build:
      context: sp
    ports:
      - 10443:10443

